'use strict';

module.exports = app => {
    app.use('/v1/academic-session', require('./modules/routes/academic-session'));
    app.use('/v1/school', require('./modules/routes/school'));
    app.use('/v1/admin', require('./modules/routes/users/admin-user'));
    app.use('/v1/student', require('./modules/routes/student'));
    app.use('/v1/teacher-user', require('./modules/routes/users/teacher-user'));
    app.use('/v1/sales-user', require('./modules/routes/users/sales-user'));
    app.use('/v1/class', require('./modules/routes/class'));
    app.use('/v1/subject', require('./modules/routes/subject'));
    app.use('/v1/class-subject', require('./modules/routes/class-subject'));
    app.use('/v1/teacher', require('./modules/routes/teacher'));
    app.use('/v1/department', require('./modules/routes/department'));
    app.use('/v1/designation', require('./modules/routes/designation'));
    app.use('/v1/staff', require('./modules/routes/staff'));
    app.use('/v1/biometric-mapping', require('./modules/routes/biometric-mapping'));
    app.use('/v1/shift', require('./modules/routes/shift'));
    app.use('/v1/class-shift', require('./modules/routes/class-shift'));
    app.use('/v1/roster', require('./modules/routes/roster'));
    app.use('/v1/attendance', require('./modules/routes/attendance'));
    app.use('/v1/leave-type', require('./modules/routes/leave-type'));
    app.use('/v1/leave-request', require('./modules/routes/leave-request'));
    app.use('/v1/leave-assignment', require('./modules/routes/leave-assignment'));
    app.use('/v1/holiday', require('./modules/routes/holiday'));
    app.use('/v1/holiday-template', require('./modules/routes/holiday-template'));
    app.use('/v1/holiday-assignment', require('./modules/routes/holiday-assignment'));
    app.use('/v1/salary-group', require('./modules/routes/salary-group'));
    app.use('/v1/salary-structure', require('./modules/routes/salary-structure'));
    app.use('/v1/payroll', require('./modules/routes/payroll'));
    app.use('/v1/salary-payment', require('./modules/routes/salary-payment'));
    app.use('/v1/staff-bank-details', require('./modules/routes/staff-bank-details'));
    app.use('/v1/device', require('./modules/routes/devices/device'));
    app.use('/v1/exam-result', require('./modules/routes/exam-result'));
    app.use('/v1/exam-result-structure', require('./modules/routes/exam-result-structure'));
    app.use('/v1/fees', require('./modules/routes/fees-collection'));
    app.use('/v1/fees-structure', require('./modules/routes/fees-structure'));
    app.use('/v1/reminder', require('./modules/routes/reminder'));
    app.use('/v1/admit-card-structure', require('./modules/routes/admit-card-structure'));
    app.use('/v1/admit-card', require('./modules/routes/admit-card'));
    app.use('/v1/issued-transfer-certificate', require('./modules/routes/issued-transfer-certificate'));
    app.use('/v1/whatsapp-message', require('./modules/routes/whatsapp-message/message-wallet'));
    app.use('/v1/payment', require('./modules/routes/payment'));
    // app.use('/v1/testimonial', require('./modules/routes/testimonial'));
    // app.use('/v1/topper', require('./modules/routes/topper'));
    // app.use('/v1/ads', require('./modules/routes/ads'));
    // app.use('/v1/banner', require('./modules/routes/banner'));
    app.use('/v1/plans', require('./modules/routes/plans'));
    app.use('/v1/board', require('./modules/routes/board'));
    app.use('/v1/id-card', require('./modules/routes/id-card'));
};